# Generated by Django 6.1 on 2026-09-12 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Science'), ('competition', 'Competition'), ('course', 'Course Project')], default='web', max_length=20)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True, help_text='Satu project dalam satu baris')),
                ('tech_stack', models.CharField(help_text='Pisahkan dengan koma', max_length=200)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-started_at'],
            },
        ),
    ]
