# Generated by Django 6.1 on 2026-09-13 13:41

import django.db.models.deletion
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=150)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('logo', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(validators=[main.models.validate_word_count])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('olimpiade', 'Olimpiade'), ('organisasi', 'Organisasi'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.journeystage')),
            ],
            options={
                'verbose_name_plural': 'Stage activities',
                'ordering': ['order', 'title'],
            },
        ),
    ]