# Generated by Django 6.1 on 2026-10-05 09:13

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(help_text='Pastikan Kapital')),
                ('issuer', models.TextField()),
                ('category', models.CharField(choices=[('swe', 'Software Engineering'), ('sde', 'Software Development'), ('dsai', 'Data Science and AI'), ('cybersec', 'Cyber Security')], default='swe', max_length=40)),
                ('issued_at', models.DateField()),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('starred_by', models.ManyToManyField(blank=True, related_name='starred_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
